[package]
name = "nothing-cli"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "nothing"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.5.51", features = ["derive"] }
uuid = { version = "=1.18.1", features = ["v4"]}
